variable "aws_region" {}
variable "air_moisture_data_processing_recommendations_lambda_role_name" {}
variable "air_temperature_data_processing_recommendations_lambda_role_name" {}
variable "brightness_data_processing_recommendations_lambda_role_name" {}
variable "soil_moisture_data_processing_recommendations_lambda_role_name" {}
variable "soil_temperature_data_processing_recommendations_lambda_role_name" {}